spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${APPLICATION_NAME}
  datasource:
    name: ${POSTGRES_DB}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}
    driver: ${DATABASE_DRIVER}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: ${DATABASE}
    database-platform: ${DATABASE_PLATFORM}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-duration: "${JWT_ACCESS_DURATION}"
  
logging:
  level:
    org.springframework.security: DEBUG
    
server:
  port: ${SERVER_PORT}