spring:
  application:
    name: Cafe Management Application
  datasource:
    name: cafe_management
    url: jdbc:postgresql://localhost:5432/cafe_management
    driver: org.postgresql.Driver
    username: postgres
    password: myPassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: DEBUG
    
server:
  port: 8081